manifest:
  self:
    path: realtek-zephyr-project
    west-commands: tool/west-commands.yml

  remotes:
    - name: rtkconnectivity
      url-base: https://github.com/rtkconnectivity

  defaults:
    remote: rtkconnectivity

  projects:
    - name: zephyr
      remote: rtkconnectivity
      revision: realtek-main-v3.7
      import:
        name-allowlist:
          - cmsis
          - hal_realtek
          - tinycrypt
          - openthread
          - mbedtls
