manifest:
  self:
    path: realtek-zephyr-project

  remotes:
    - name: rtkconnectivity
      url-base: https://github.com/rtkconnectivity

  projects:
    - name: zephyr
      remote: rtkconnectivity
      revision: realtek-main-v3.5.0
      import:
        name-allowlist:
          - cmsis
          - hal_realtek
          - tinycrypt
          - openthread
          - mbedtls
    - name: matter
      remote: rtkconnectivity
      repo-path: connectedhomeip
      path: modules/lib/matter
      revision: v1.3.0.0