manifest:
  self:
    path: realtek-zephyr-project
    west-commands: tool/west-commands.yml

  remotes:
    - name: rtkconnectivity
      url-base: https://github.com/rtkconnectivity

  defaults:
    remote: rtkconnectivity

  projects:
    - name: zephyr
      remote: rtkconnectivity
      revision: v3.7-rtk-00.01.01
      import:
        name-allowlist:
          - cmsis
          - hal_realtek
          - tinycrypt
          - openthread
          - mbedtls

    #
    # Realtek based overrides of Zephyr modules and additional
    # added modules
    #
    - name: hal_realtek
      revision: a0a394a583ab8f0c37d56aefa65da834fe411878
      path: modules/hal/realtek
      groups:
        - hal
