manifest:
  self:
    path: realtek-zephyr-project

  remotes:
    - name: rtkconnectivity
      url-base: https://github.com/rtkconnectivity
    - name: project-chip
      url-base: https://github.com/project-chip

  projects:
    - name: zephyr
      remote: rtkconnectivity
      revision: realtek-main-v3.7
      import:
        name-allowlist:
          - cmsis
          - hal_realtek
          - tinycrypt
          - openthread
          - mbedtls
    - name: connectedhomeip
      remote: project-chip
      repo-path: connectedhomeip
      path: modules/lib/connectedhomeip
      revision: master
