manifest:
  self:
    path: realtek-zephyr-project

  remotes:
    - name: rtkconnectivity
      url-base: https://github.com/rtkconnectivity

  projects:
    - name: zephyr
      remote: rtkconnectivity
      revision: realtek-main-v3.7
      import:
        name-allowlist:
          - cmsis
          - hal_realtek
          - tinycrypt
          - openthread
          - mbedtls
