manifest:
  self:
    path: realtek-zephyr-project
    west-commands: tool/west-commands.yml

  remotes:
    - name: rtkconnectivity
      url-base: https://github.com/rtkconnectivity
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos

  defaults:
    remote: rtkconnectivity

  projects:
    - name: zephyr
      remote: rtkconnectivity
      revision: realtek-main-v4.4
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_realtek
          - mbedtls
          - tf-psa-crypto
          - segger
          - cmsis-dsp
          - cmsis-nn
          - mldsa-native
          - littlefs
          - fatfs
          - mcuboot
          - zcbor
          - mipi-sys-t

    #
    # Realtek based overrides of hal_realtek modules
    #
    - name: hal_realtek
      remote: rtkconnectivity
      revision: hal_realtek_v4.4
      path: modules/hal/realtek
      groups:
        - hal
