manifest:
  self:
    path: realtek-zephyr-project
    west-commands: tool/west-commands.yml

  remotes:
    - name: rtkconnectivity
      url-base: https://github.com/rtkconnectivity

  defaults:
    remote: rtkconnectivity

  projects:
    - name: zephyr
      remote: rtkconnectivity
      revision: v3.7-rtk-00.01.00
      import:
        name-allowlist:
          - cmsis
          - hal_realtek
          - tinycrypt
          - openthread
          - mbedtls

    #
    # Realtek based overrides of Zephyr modules and additional
    # added modules
    #
    - name: hal_realtek
      revision: 88784d4eb606c7c4579ae1a24292dae3172aaaea
      path: modules/hal/realtek
      groups:
        - hal
