CONFIG_BT=y
CONFIG_REALTEK_PPT=y
CONFIG_PWM=y
CONFIG_COUNTER=y

CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_HID=y
CONFIG_USB_DEVICE_PRODUCT="Zephyr HID sample"
CONFIG_USB_DEVICE_PID=0x0006
CONFIG_USB_HID_BOOT_PROTOCOL=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n
CONFIG_WATCHDOG=y
CONFIG_REALTEK_USING_SDK_LIB=y
CONFIG_REALTEK_USING_PPT_SYNC_MASTER=n
CONFIG_REALTEK_USING_PPT_SYNC_SLAVE=y

CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y

CONFIG_LOG=y