CONFIG_BT=y
CONFIG_BT_SMP=y
CONFIG_BT_DIS=y
CONFIG_BT_BAS=y

CONFIG_BT_PERIPHERAL=y
CONFIG_BT_RTL87X2G=y
#enable link key storage
CONFIG_BT_SETTINGS=y
CONFIG_BT_KEYS_OVERWRITE_OLDEST=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_BT_MAX_CONN=2
CONFIG_BT_MAX_PAIRED=1
#enable to send voice data
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_L2CAP_TX_MTU=247
#enable DLE
CONFIG_BT_USER_DATA_LEN_UPDATE=y
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251

# CONFIG_FPU=y
# CONFIG_FP_HARDABI=y
# CONFIG_FP16=y
# CONFIG_FP16_IEEE=y

CONFIG_KSCAN=y
CONFIG_RTL87X2G_KEYSCAN_AUTOSCAN_MODE=n
CONFIG_RTL87X2G_KEYSCAN_MANUAL_SCAN_INTERVAL_MSEC=50
CONFIG_DMA=y
#audio configurations
CONFIG_AUDIO=y
CONFIG_AUDIO_CODEC=y
CONFIG_I2S=y
CONFIG_I2S_RTL87X2G_RX=y
# CONFIG_I2S_RTL8762G_TX=y
CONFIG_REALTEK_VOICE=y

# CONFIG_PM=y
# CONFIG_PM_DEVICE=y

CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_HEAP_MEM_POOL_SIZE=8900
#default 1024 is not enough when ir learning
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_LOG=y
# #default 768 is not enough
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=1024
CONFIG_LOG_BUFFER_SIZE=2048